# Understanding the datatyes, null values , inconsistency of dataset

In [15]:
import pandas as pd
import numpy as np

In [16]:
# to load csv dataset
data = pd.read_csv('smart_hospital_appointment_dataset.csv')

In [7]:
# to get rows and columns in dataset
data.shape

(10000, 26)

In [5]:
#first 6 rows of dataset
data.head(6)

,patient_id,age,gender,city,bmi,chronic_disease,appointment_type,department,symptoms,severity_level,...,waiting_time_minutes,previous_appointments,missed_previous_appointments,hospital_rating,emergency_case,patient_satisfaction_score,medicine_cost,test_cost,total_bill,appointment_status
0,PAT_10000,52,Male,Mumbai,19.6,Hypertension,Scheduled,Neurology,Headache,Low,...,43,7,2,3.0,0,8.6,869,413,1936.0,Completed
1,PAT_10001,21,Female,Mumbai,25.3,NaN,Scheduled,Neurology,Headache,Low,...,44,11,5,3.5,0,8.8,786,875,1356.6,No Show
2,PAT_10002,51,Female,Bangalore,21.9,NaN,Scheduled,Dermatology,Skin Allergy,Low,...,33,9,0,4.4,0,10.0,466,427,1108.8,No Show
3,PAT_10003,78,Female,Delhi,31.7,NaN,Walk-in,Orthopedics,Joint Pain,Low,...,59,13,3,4.1,0,8.1,921,401,1417.5,Completed
4,PAT_10004,62,Female,Mumbai,24.7,Hypertension,Scheduled,Ophthalmology,Eye Irritation,Low,...,42,4,0,3.5,0,8.9,152,216,746.9,Completed
5,PAT_10005,41,Female,Jaipur,25.3,NaN,Walk-in,Pulmonology,Cough,Low,...,20,8,2,3.4,0,10.0,571,498,1304.1,Completed

In [6]:
#last 5 rows of dataset
data.tail(5)

,patient_id,age,gender,city,bmi,chronic_disease,appointment_type,department,symptoms,severity_level,...,waiting_time_minutes,previous_appointments,missed_previous_appointments,hospital_rating,emergency_case,patient_satisfaction_score,medicine_cost,test_cost,total_bill,appointment_status
9995,PAT_19995,15,Male,Nagpur,17.2,NaN,Walk-in,Neurology,Headache,High,...,8,5,1,4.8,0,10.0,7218,11425,13643.0,Completed
9996,PAT_19996,70,Female,Pune,36.3,NaN,Walk-in,Cardiology,Chest Pain,Medium,...,19,0,0,3.1,0,10.0,4671,3558,6234.9,Completed
9997,PAT_19997,64,Female,Kolkata,27.3,Diabetes,Emergency,Ophthalmology,Eye Irritation,Low,...,47,8,3,4.6,1,9.2,189,276,879.0,Completed
9998,PAT_19998,21,Male,Hyderabad,27.0,Hypertension,Walk-in,Gastroenterology,Stomach Pain,High,...,12,11,7,3.1,0,10.0,8044,7855,11531.1,Completed
9999,PAT_19999,82,Male,Jaipur,15.4,Hypertension,Scheduled,General Medicine,Fever,Medium,...,24,2,0,5.0,0,10.0,2214,2843,5685.0,No Show

In [8]:
data.info()
#information about the columns of the dataset about datatypes

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   patient_id                    10000 non-null  str
 1   age                           10000 non-null  int64
 2   gender                        10000 non-null  str
 3   city                          10000 non-null  str
 4   bmi                           10000 non-null  float64
 5   chronic_disease               5550 non-null   str
 6   appointment_type              10000 non-null  str
 7   department                    10000 non-null  str
 8   symptoms                      10000 non-null  str
 9   severity_level                10000 non-null  str
 10  doctor_experience_years       10000 non-null  int64
 11  consultation_fee              10000 non-null  int64
 12  insurance                     10000 non-null  str
 13  appointment_day               10000 non-null  str
 14  appointment_month             10000 non-null  str
 15  booking_to_appointment_days   10000 non-null  int64
 16  waiting_time_minutes          10000 non-null  int64
 17  previous_appointments         10000 non-null  int64
 18  missed_previous_appointments  10000 non-null  int64
 19  hospital_rating               10000 non-null  float64
 20  emergency_case                10000 non-null  int64
 21  patient_satisfaction_score    10000 non-null  float64
 22  medicine_cost                 10000 non-null  int64
 23  test_cost                     10000 non-null  int64
 24  total_bill                    10000 non-null  float64
 25  appointment_status            10000 non-null  str
dtypes: float64(4), int64(10), str(12)
memory usage: 2.0 MB

In [10]:
# to check sum of total null values in each column 
data.isnull().sum()
# chronic disease has 4450 null values NO DROP FOR NULL VALUES as it represent patient has no chronic disease

patient_id                         0
age                                0
gender                             0
city                               0
bmi                                0
chronic_disease                 4450
appointment_type                   0
department                         0
symptoms                           0
severity_level                     0
doctor_experience_years            0
consultation_fee                   0
insurance                          0
appointment_day                    0
appointment_month                  0
booking_to_appointment_days        0
waiting_time_minutes               0
previous_appointments              0
missed_previous_appointments       0
hospital_rating                    0
emergency_case                     0
patient_satisfaction_score         0
medicine_cost                      0
test_cost                          0
total_bill                         0
appointment_status                 0
dtype: int64

In [17]:
#get numerical (statistical Information) of the dataset like mean, min , max ,standard deviation
data.describe()
# mean of age is 45 , min 1 max 89
# mean of waiting time is 25min , minimum is 1min maximum is 59 min
# avg fees is 606 , min 220 , max 999

,age,bmi,doctor_experience_years,consultation_fee,booking_to_appointment_days,waiting_time_minutes,previous_appointments,missed_previous_appointments,hospital_rating,emergency_case,patient_satisfaction_score,medicine_cost,test_cost,total_bill
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,45.000400,24.010890,15.399000,606.860700,12.754500,25.203900,7.019200,1.416700,3.989940,0.148600,9.701980,5053.976100,3932.363100,7881.768000
std,25.862836,3.935325,8.604069,180.246694,9.405715,14.862961,4.334502,1.383637,0.579424,0.355712,0.537897,5618.208887,4165.875586,7904.071155
min,1.000000,15.000000,1.000000,220.000000,0.000000,1.000000,0.000000,0.000000,3.000000,0.000000,7.600000,100.000000,0.000000,331.800000
25%,22.000000,21.300000,8.000000,461.000000,4.000000,13.000000,3.000000,0.000000,3.500000,0.000000,9.600000,758.750000,748.000000,1598.100000
50%,45.000000,24.000000,15.000000,609.000000,12.000000,23.000000,7.000000,1.000000,4.000000,0.000000,10.000000,2833.000000,2345.000000,4631.550000
75%,68.000000,26.700000,23.000000,752.000000,21.000000,35.000000,11.000000,2.000000,4.500000,0.000000,10.000000,7499.500000,5817.500000,13280.000000
max,89.000000,39.800000,30.000000,999.000000,29.000000,59.000000,14.000000,9.000000,5.000000,1.000000,10.000000,19996.000000,14992.000000,34894.000000

In [37]:
data.describe(include = 'object')
#describing categorical data of dataset like unique, top , frequency , count

C:\Users\HP\AppData\Local\Temp\ipykernel_12996\2159399482.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include = 'object')

,patient_id,gender,city,chronic_disease,appointment_type,department,symptoms,severity_level,insurance,appointment_day,appointment_month,appointment_status
count,10000,10000,10000,5550,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,2,10,4,3,10,10,3,2,6,12,3
top,PAT_10000,Male,Delhi,Diabetes,Scheduled,Cardiology,Chest Pain,Medium,Yes,Saturday,February,Completed
freq,1,5005,1071,2034,5433,1075,1075,3597,6008,1724,878,8339

In [30]:
#checking for dublicate rows in data
duplicate_count = data.duplicated().sum()

In [22]:
data["gender"].unique()
#CHECKING UNIQUE GENDER FOR ANY MISTAKE

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [24]:
#count of total Unique gender
data["gender"].nunique()

2

In [26]:
#to get categorical columns 
categorical_columns = data.select_dtypes(include=["object", "string"]).columns

In [28]:
for col in categorical_columns:
    print(f"\nColumn: {col}")
    print(data[col].unique())

Column: patient_id
<StringArray>
['PAT_10000', 'PAT_10001', 'PAT_10002', 'PAT_10003', 'PAT_10004', 'PAT_10005',
 'PAT_10006', 'PAT_10007', 'PAT_10008', 'PAT_10009',
 ...
 'PAT_19990', 'PAT_19991', 'PAT_19992', 'PAT_19993', 'PAT_19994', 'PAT_19995',
 'PAT_19996', 'PAT_19997', 'PAT_19998', 'PAT_19999']
Length: 10000, dtype: str

Column: gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Column: city
<StringArray>
[   'Mumbai', 'Bangalore',     'Delhi',    'Jaipur',   'Kolkata',   'Chennai',
 'Hyderabad',      'Pune', 'Ahmedabad',    'Nagpur']
Length: 10, dtype: str

Column: chronic_disease
<StringArray>
['Hypertension', nan, 'Diabetes', 'Asthma', 'Heart Disease']
Length: 5, dtype: str

Column: appointment_type
<StringArray>
['Scheduled', 'Walk-in', 'Emergency']
Length: 3, dtype: str

Column: department
<StringArray>
[       'Neurology',      'Dermatology',      'Orthopedics',
    'Ophthalmology',      'Pulmonology', 'General Medicine',
       'Cardiology', 'Gastroenterology',           'Dental',
       'Gynecology']
Length: 10, dtype: str

Column: symptoms
<StringArray>
[         'Headache',      'Skin Allergy',        'Joint Pain',
    'Eye Irritation',             'Cough',             'Fever',
        'Chest Pain',      'Stomach Pain',       'Dental Pain',
 'Pregnancy Checkup']
Length: 10, dtype: str

Column: severity_level
<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

Column: insurance
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: appointment_day
<StringArray>
['Friday', 'Saturday', 'Thursday', 'Wednesday', 'Monday', 'Tuesday']
Length: 6, dtype: str

Column: appointment_month
<StringArray>
[ 'February',  'November',      'June',   'October',       'May',     'April',
  'December',    'August',      'July',     'March', 'September',   'January']
Length: 12, dtype: str

Column: appointment_status
<StringArray>
['Completed', 'No Show', 'Cancelled']
Length: 3, dtype: str

In [39]:
#to verify that all data is genuine and realistic
numerical_columns = data.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_columns:
    print(f"\nColumn: {col}")
    print("Minimum:", data[col].min())
    print("Maximum:", data[col].max())

Column: age
Minimum: 1
Maximum: 89

Column: bmi
Minimum: 15.0
Maximum: 39.8

Column: doctor_experience_years
Minimum: 1
Maximum: 30

Column: consultation_fee
Minimum: 220
Maximum: 999

Column: booking_to_appointment_days
Minimum: 0
Maximum: 29

Column: waiting_time_minutes
Minimum: 1
Maximum: 59

Column: previous_appointments
Minimum: 0
Maximum: 14

Column: missed_previous_appointments
Minimum: 0
Maximum: 9

Column: hospital_rating
Minimum: 3.0
Maximum: 5.0

Column: emergency_case
Minimum: 0
Maximum: 1

Column: patient_satisfaction_score
Minimum: 7.6
Maximum: 10.0

Column: medicine_cost
Minimum: 100
Maximum: 19996

Column: test_cost
Minimum: 0
Maximum: 14992

Column: total_bill
Minimum: 331.8
Maximum: 34894.0

All categories have standard values and realistic numerical values .
The dataset contains 10,000 rows and 26 columns with No dublicate values.
Missing values exist only in the chronic_disease column (4,450 records), which indicates patients without any chronic conditions and will be handled during data cleaning.